name: Deploy Angular App to GitHub Pages

on:
  # Esegui il workflow quando viene effettuato un push nella branch main
  push:
    branches:
      - main

  # Esegui il workflow anche manualmente
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Usa la versione di Node.js richiesta da Angular
          
      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npx run build --  --configuration production --output-path=dist/browser --base-href="/lucadominici/"
        # Sostituisci <repository-name> con il nome del tuo repository

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser
